apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blincra
  description: test
  annotations:
    backstage.io/techdocs-ref: github:https://github.com/pxdbackstagepoc/ben-cra
spec:
  type: website
  lifecycle: experimental
  owner: benlin1994



